name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Create Service Account file
        run: echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > secrets.json
      - name: Install Dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        env:
          GOOGLE_APPLICATION_CREDENTIALS: secrets.json 
          SHEET_ID: ${{ vars.SHEET_ID }}